const KEY = 'photocard-collection-v1';
const state = { cards: [], layouts: [], selected: [], activeSlot: 0, grid: [null, null, null, null] };
const $ = (id) => document.getElementById(id);
const formIds = ['nameInput','memberInput','albumInput','sourceInput','sourceDetailInput','marketPriceInput','purchasePriceInput','orderDateInput','statusInput','likeInput','quantityInput','lookInput','noteInput'];
const crop = { image:null, scale:1, minScale:1, x:0, y:0, dragging:false, startX:0, startY:0, originX:0, originY:0 };
const escapeHTML = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function persist(){ localStorage.setItem(KEY, JSON.stringify({ cards: state.cards, layouts: state.layouts })); }
function load(){ try { const data = JSON.parse(localStorage.getItem(KEY)); if(data){ state.cards = data.cards || []; state.layouts = data.layouts || []; } } catch { toast('没有读取到原来的数据'); } }
function toast(message){ const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200); }
function imageHTML(card, cls=''){ return card?.image ? `<img class="${cls}" src="${card.image}" alt="${escapeHTML(card.name)}">` : `<div class="fallback ${cls}">✦</div>`; }
function star(n){ return '★'.repeat(Number(n||0))+'☆'.repeat(5-Number(n||0)); }
function cardHTML(card, compact=false){ return `<article class="pcard ${state.selected.includes(card.id)?'selected':''}" data-id="${card.id}"><div class="pcard-image">${imageHTML(card)}<span class="status">${escapeHTML(card.status)}</span>${Number(card.quantity)>1?`<span class="quantity">×${card.quantity}</span>`:''}<span class="check">✓</span></div><div class="pcard-info"><div class="pcard-title">${escapeHTML(card.name)}</div><div class="pcard-meta">${escapeHTML(card.member)}${card.album?' · '+escapeHTML(card.album):''}</div>${compact?'':`<div class="stars">${star(card.like)}</div>`}<button class="edit-card" type="button">编辑</button></div></article>`; }
function filteredCards(){ const search=$('searchInput').value.trim().toLowerCase(); const f={status:$('statusFilter').value,member:$('memberFilter').value,album:$('albumFilter').value,source:$('sourceFilter').value,like:$('likeFilter').value}; let cards=state.cards.filter(c=> (!search || [c.name,c.member,c.album,c.source].some(x=>(x||'').toLowerCase().includes(search))) && (!f.status||c.status===f.status) && (!f.member||c.member===f.member) && (!f.album||c.album===f.album) && (!f.source||c.source===f.source) && (!f.like||String(c.like)===f.like)); const sorting=$('sortSelect').value; return cards.sort((a,b)=> sorting==='like'?b.like-a.like:sorting==='market'?(Number(b.marketPrice)||0)-(Number(a.marketPrice)||0):sorting==='name'?a.name.localeCompare(b.name,'zh-CN'):(b.createdAt||0)-(a.createdAt||0)); }
function populateFilters(){ [['memberFilter','member'],['albumFilter','album'],['sourceFilter','source']].forEach(([id,key])=>{const select=$(id),value=select.value; select.innerHTML=`<option value="">所有${id==='memberFilter'?'成员':id==='albumFilter'?'专辑 / 系列':'来源'}</option>`; [...new Set(state.cards.map(c=>c[key]).filter(Boolean))].sort().forEach(v=>select.insertAdjacentHTML('beforeend',`<option value="${escapeHTML(v)}">${escapeHTML(v)}</option>`)); select.value=value;}); }
function renderLibrary(){ populateFilters(); const cards=filteredCards(); $('cardCount').textContent=state.cards.length; $('cardGrid').innerHTML=cards.map(c=>cardHTML(c)).join(''); $('emptyLibrary').classList.toggle('hidden',state.cards.length>0); $('cardGrid').classList.toggle('hidden',state.cards.length===0); $('selectionBar').classList.toggle('hidden',state.selected.length===0); $('selectionText').textContent=`已选 ${state.selected.length} / 4`; }
function renderWish(){ const cards=state.cards.filter(c=>c.status==='想收').sort((a,b)=>(b.like-a.like)||((b.createdAt||0)-(a.createdAt||0))); $('wishGrid').innerHTML=cards.map(c=>cardHTML(c)).join(''); $('wishGrid').classList.toggle('hidden',cards.length===0); $('emptyWish').classList.toggle('hidden',cards.length>0); }
function renderLooks(){ const groups={}; state.cards.filter(c=>c.look?.trim()).forEach(c=>(groups[c.look.trim()]??=[]).push(c)); const names=Object.keys(groups).sort((a,b)=>b.localeCompare(a,'zh-CN')); $('looksList').innerHTML=names.map(name=>`<section><div class="look-heading"><h2>${escapeHTML(name)}</h2><span>${groups[name].length} 张不同小卡</span></div><div class="look-cards">${groups[name].map(c=>cardHTML(c,true)).join('')}</div></section>`).join(''); $('emptyLooks').classList.toggle('hidden',names.length>0); }
function renderLookOptions(){ const names=[...new Set(state.cards.map(card=>card.look?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN')); $('looksOptions').replaceChildren(...names.map(name=>Object.assign(document.createElement('option'),{value:name}))); $('lookInput').setAttribute('list','looksOptions'); }
function renderLookActions(){ document.querySelectorAll('.look-heading').forEach(heading=>{const button=document.createElement('button');button.className='small-action add-to-look';button.dataset.look=heading.querySelector('h2').textContent;button.textContent='＋ 添加到这个造型';heading.append(button);}); }
function renderGrid(){ const cards=state.grid.map(id=>state.cards.find(c=>c.id===id)); $('fourGrid').innerHTML=cards.map((card,i)=>`<div class="slot ${state.activeSlot===i?'active':''}" data-slot="${i}">${card?imageHTML(card):'<div class="fallback">＋</div>'}<span class="slot-label">${i+1}</span><div class="slot-controls"><button data-move="${i},-1" aria-label="向前移动">←</button><button data-move="${i},1" aria-label="向后移动">→</button></div></div>`).join(''); const available=state.cards; $('replaceCards').innerHTML=available.map(c=>`<button class="mini-card ${state.grid[state.activeSlot]===c.id?'active':''}" data-replace="${c.id}">${c.image?`<img src="${c.image}" alt="">`:'<div class="mini-fallback">✦</div>'}<span>${escapeHTML(c.name)}</span></button>`).join('') || '<p class="subcopy">先添加小卡，才能开始试摆。</p>'; $('savedLayouts').innerHTML=state.layouts.slice().reverse().map(l=>`<button class="saved-layout" data-layout="${l.id}"><div class="saved-preview">${l.cards.map(id=>{const c=state.cards.find(x=>x.id===id);return c?.image?`<img src="${c.image}" alt="">`:'<div></div>';}).join('')}</div><p>${escapeHTML(l.name)}</p><small>${new Date(l.createdAt).toLocaleDateString('zh-CN')}</small></button>`).join('') || '<p class="subcopy">保存后的四宫格会出现在这里。</p>'; }
function render(){ renderLibrary(); renderWish(); renderLooks(); renderLookOptions(); renderLookActions(); renderGrid(); }
function openDialog(card){ $('cardForm').reset(); $('cardId').value=card?.id||''; $('dialogTitle').textContent=card?'编辑小卡':'添加小卡'; $('dialogEyebrow').textContent=card?'EDIT CARD':'NEW CARD'; $('deleteCard').classList.toggle('hidden',!card); $('imagePreview').style.display='none'; $('uploadLabel').style.display='block'; $('removeImage').classList.add('hidden'); if(card){ formIds.forEach(id=>$(id).value=card[id.replace('Input','')] ?? ''); if(card.image) setPreview(card.image); } $('cardDialog').showModal(); }
function setPreview(src){ $('imagePreview').src=src; $('imagePreview').style.display='block'; $('uploadLabel').style.display='none'; $('removeImage').classList.remove('hidden'); }
function constrainCrop(){ const canvas=$('cropCanvas'); const maxX=Math.max(0,(crop.image.naturalWidth*crop.scale-canvas.width)/2), maxY=Math.max(0,(crop.image.naturalHeight*crop.scale-canvas.height)/2); crop.x=Math.max(-maxX,Math.min(maxX,crop.x)); crop.y=Math.max(-maxY,Math.min(maxY,crop.y)); }
function drawCrop(){ if(!crop.image)return; const canvas=$('cropCanvas'),ctx=canvas.getContext('2d'),w=crop.image.naturalWidth*crop.scale,h=crop.image.naturalHeight*crop.scale; constrainCrop(); ctx.fillStyle='#14223c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingQuality='high';ctx.drawImage(crop.image,canvas.width/2-w/2+crop.x,canvas.height/2-h/2+crop.y,w,h); }
function startCrop(src){ const image=new Image(); image.onload=()=>{const canvas=$('cropCanvas');crop.image=image;crop.minScale=Math.max(canvas.width/image.naturalWidth,canvas.height/image.naturalHeight);crop.scale=crop.minScale;crop.x=0;crop.y=0;$('cropZoom').value='1';drawCrop();$('cropDialog').showModal();}; image.onerror=()=>toast('这张照片暂时无法读取，请换一张试试');image.src=src; }
function saveCard(){ if(!$('cardForm').reportValidity()) return; const id=$('cardId').value||crypto.randomUUID(); const old=state.cards.find(c=>c.id===id); const card={id,image:$('imagePreview').style.display!=='none'?$('imagePreview').src:'',name:$('nameInput').value.trim(),member:$('memberInput').value.trim(),album:$('albumInput').value.trim(),source:$('sourceInput').value.trim(),sourceDetail:$('sourceDetailInput').value.trim(),marketPrice:$('marketPriceInput').value,purchasePrice:$('purchasePriceInput').value,orderDate:$('orderDateInput').value,status:$('statusInput').value,like:$('likeInput').value,quantity:$('quantityInput').value,look:$('lookInput').value.trim(),note:$('noteInput').value.trim(),createdAt:old?.createdAt||Date.now()}; const index=state.cards.findIndex(c=>c.id===id); if(index>=0) state.cards[index]=card; else state.cards.push(card); try{persist();}catch{toast('图片太大，浏览器空间不够；请换一张更小的图片');return;} $('cardDialog').close(); render(); toast(old?'小卡已更新':'小卡已加入卡册'); }
function deleteCard(){ const id=$('cardId').value; const card=state.cards.find(c=>c.id===id); if(!card||!confirm(`删除「${card.name}」？`))return; state.cards=state.cards.filter(c=>c.id!==id); state.selected=state.selected.filter(x=>x!==id); state.grid=state.grid.map(x=>x===id?null:x); state.layouts=state.layouts.filter(l=>!l.cards.includes(id)); persist(); $('cardDialog').close(); render(); toast('已删除小卡'); }
document.addEventListener('click',e=>{const addWish=e.target.closest('.add-wish'); if(addWish){openDialog();$('statusInput').value='想收';return;} const add=e.target.closest('.add-card'); if(add)openDialog(); const nav=e.target.closest('[data-view]'); if(nav){document.querySelectorAll('.view,.nav-link').forEach(x=>x.classList.remove('active')); $(nav.dataset.view).classList.add('active'); nav.classList.add('active'); if(nav.dataset.view==='grid')renderGrid(); window.scrollTo({top:0,behavior:'smooth'});} const card=e.target.closest('.pcard'); if(card){ if(e.target.closest('.look-cards,#wishGrid')){ openDialog(state.cards.find(c=>c.id===card.dataset.id));return; } const id=card.dataset.id; if(state.selected.includes(id))state.selected=state.selected.filter(x=>x!==id); else if(state.selected.length<4)state.selected.push(id); else{toast('四宫格最多选 4 张');return;} renderLibrary(); } const slot=e.target.closest('.slot'); if(slot&&!e.target.closest('[data-move]')){state.activeSlot=Number(slot.dataset.slot);renderGrid();} const move=e.target.closest('[data-move]'); if(move){const [i,d]=move.dataset.move.split(',').map(Number),j=i+d;if(j>=0&&j<4){[state.grid[i],state.grid[j]]=[state.grid[j],state.grid[i]];state.activeSlot=j;renderGrid();}} const replacement=e.target.closest('[data-replace]'); if(replacement){state.grid[state.activeSlot]=replacement.dataset.replace;renderGrid();} const layout=e.target.closest('[data-layout]');if(layout){const found=state.layouts.find(l=>l.id===layout.dataset.layout); state.grid=[...found.cards]; $('layoutName').value=found.name; renderGrid();toast('已载入组合');} });
document.addEventListener('click',e=>{const addToLook=e.target.closest('.add-to-look');if(!addToLook)return;openDialog();$('lookInput').value=addToLook.dataset.look;});
document.addEventListener('click',e=>{const edit=e.target.closest('.edit-card');if(!edit)return;e.stopPropagation();openDialog(state.cards.find(card=>card.id===edit.closest('.pcard').dataset.id));},true);
['searchInput','statusFilter','memberFilter','albumFilter','sourceFilter','likeFilter','sortSelect'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',renderLibrary));
$('openGrid').onclick=()=>{ state.grid=[...state.selected]; while(state.grid.length<4)state.grid.push(null); state.activeSlot=0; document.querySelector('[data-view="grid"]').click(); };
$('clearSelection').onclick=()=>{state.selected=[];renderLibrary();};
$('imageInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>12*1024*1024){toast('请选小于 12MB 的图片');e.target.value='';return;}const r=new FileReader();r.onload=()=>startCrop(r.result);r.readAsDataURL(file)};
$('cropZoom').oninput=e=>{crop.scale=crop.minScale*Number(e.target.value);drawCrop();};
$('cropCanvas').addEventListener('pointerdown',e=>{if(!crop.image)return;crop.dragging=true;crop.startX=e.clientX;crop.startY=e.clientY;crop.originX=crop.x;crop.originY=crop.y;e.currentTarget.setPointerCapture(e.pointerId);});
$('cropCanvas').addEventListener('pointermove',e=>{if(!crop.dragging)return;crop.x=crop.originX+e.clientX-crop.startX;crop.y=crop.originY+e.clientY-crop.startY;drawCrop();});
$('cropCanvas').addEventListener('pointerup',()=>crop.dragging=false);
$('applyCrop').onclick=()=>{setPreview($('cropCanvas').toDataURL('image/jpeg',.9));$('cropDialog').close();$('imageInput').value='';};
$('cancelCrop').onclick=$('cancelCropText').onclick=()=>{$('cropDialog').close();$('imageInput').value='';};
$('removeImage').onclick=()=>{$('imagePreview').src='';$('imagePreview').style.display='none';$('uploadLabel').style.display='block';$('removeImage').classList.add('hidden');$('imageInput').value='';};
$('closeDialog').onclick=$('cancelDialog').onclick=()=>$('cardDialog').close(); $('cardForm').addEventListener('submit',e=>{e.preventDefault();saveCard();}); $('deleteCard').onclick=deleteCard;
$('saveLayout').onclick=()=>{if(state.grid.every(x=>!x)){toast('先放进至少一张小卡');return;}const name=$('layoutName').value.trim()||`四宫格 ${new Date().toLocaleDateString('zh-CN')}`;state.layouts.push({id:crypto.randomUUID(),name,cards:[...state.grid],createdAt:Date.now()});persist();renderGrid();toast('组合已保存');};
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),cards:state.cards,layouts:state.layouts},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`我的小卡册备份-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);toast('备份已导出');};
load(); render();
